services:
  cloudquery:
    image: ghcr.io/cloudquery/cloudquery:latest
    command: sync --cq-dir /cache/.cq --log-console --no-log-file --telemetry-level none /config.yml
    environment:
      CLOUDQUERY_API_KEY: ${CLOUDQUERY_API_KEY}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}
    volumes:
    - ./config.yaml:/config.yml
    - ./.cq:/cache/.cq
    - ~/.aws:/root/.aws
  postgres:
    image: postgres:latest
    command: -c wal_level=logical
    restart: unless-stopped
    volumes:
      - ./scripts:/var/lib/postgresql/scripts/
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - '3000:3000'