{
 "title": "Sample Security Policies Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "EC2 Instances with public IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    'EC2 instances should not have a public IP address' as title,\n    account_id,\n    instance_id as resource_id,\n    case when\n        public_ip_address is not null\n        then 'fail'\n        else 'pass'\n    end as status\nfrom aws_ec2_instances"
    }
   ]
  },
  {
   "title": "AWS EC2 Security groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n        account_id,\n        region,\n        group_name,\n        arn,\n        group_id as id,\n        vpc_id,\n        (i->>'FromPort')::integer AS from_port,\n        (i->>'ToPort')::integer AS to_port,\n        i->>'IpProtocol' AS ip_protocol,\n        ip_ranges->>'CidrIp' AS ip,\n        ip6_ranges->>'CidrIpv6' AS ip6\n    from aws_ec2_security_groups, JSONB_ARRAY_ELEMENTS(aws_ec2_security_groups.ip_permissions) as i\n    LEFT JOIN JSONB_ARRAY_ELEMENTS(i->'IpRanges') as ip_ranges ON true\n    LEFT JOIN JSONB_ARRAY_ELEMENTS(i->'Ipv6Ranges') as ip6_ranges ON true;"
    }
   ]
  },
  {
   "title": "EC2 EBS default encryption enabled",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  'EBS default encryption should be enabled' as title,\n  account_id,\n  concat(account_id,':',region) as resource_id,\n  case when\n    ebs_encryption_enabled_by_default is distinct from true\n    then 'fail'\n    else 'pass'\n  end as status\nfrom aws_ec2_regional_configs"
    }
   ]
  },
  {
   "title": "VPC Default SG public inbound/outbound policy",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  'The VPC default security group should not allow inbound and outbound traffic' as title,\n  account_id,\n  arn,\n  case when\n      group_name='default' \n      AND (jsonb_array_length(ip_permissions) > 0\n      OR jsonb_array_length(ip_permissions_egress) > 0)\n      then 'fail'\n      else 'pass'\n  end\nfrom\n    aws_ec2_security_groups;"
    }
   ]
  }
 ]
}